---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  ansible-lint .
  yamllint .


platforms:
  - name: instance
    image: geerlingguy/docker-centos8-ansible:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
# - name: debian-10
#   hostname: debian
#   image: mpaivabarbosa/molecule-systemd-debian:10
#   command: /sbin/init
#   volumes:
#     - /sys/fs/cgroup:/sys/fs/cgroup:rw
#   cgroupns_mode: host
#   privileged: true
#   pre_build_image: true

provisioner:
  name: ansible
  
verifier:
  name: ansible
