---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  ansible-lint .
  yamllint .


platforms:
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-debian10-ansible:latest
    name: debian10-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: geerlingguy/docker-ubuntu2004-ansible:latest
  #   name: ubuntu-20-systemd
  #   platform: amd64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: geerlingguy/docker-fedora37-ansible:latest
  #   name: fedora37-systemd
  #   platform: amd64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible

verifier:
  name: ansible
